## ITP4514 - Lecture 2 - Code Examples

In [1]:
mix = [1, True, 'Alan'] # List items can be of any data type 
fruits=['apple','durian','orange','banana','strawberry','mango','starfruit','rambutan']
print(fruits) #print all items
print(fruits[-1])

#This will return the items from position 1 to 5.
#The first item is position 0 and the LAST item "mango" is NOT included
print(fruits[1:5])

print(fruits[:5]) # extract value from poistion 0 to 5
print(fruits[5:]) # extract value from position 5 to the last one

# extract items from "banana" (-5) to, but NOT including "rambutan" (-1)
print(fruits[-5:-1])

['apple', 'durian', 'orange', 'banana', 'strawberry', 'mango', 'starfruit', 'rambutan']
rambutan
['durian', 'orange', 'banana', 'strawberry']
['apple', 'durian', 'orange', 'banana', 'strawberry']
['mango', 'starfruit', 'rambutan']
['banana', 'strawberry', 'mango', 'starfruit']


In [2]:
fruits=['apple', 'durian', 'orange', 'banana', 'pear', 'duku', 'langsat', 'grape']
if "guava" in fruits: # check if a fruit exists in the list
  print("Yes, the fruit is available in the fruit list") 

print(len(fruits)) # check the size of the list
fruits.remove("orange") # remove the item name
print(fruits)
fruits.append("longan") # add another longan
print(fruits)

# remove the item at position 5 and assign to variable fruit
fruit = fruits.pop(5) 
print(fruits)
print(fruit)

8
['apple', 'durian', 'banana', 'pear', 'duku', 'langsat', 'grape']
['apple', 'durian', 'banana', 'pear', 'duku', 'langsat', 'grape', 'longan']
['apple', 'durian', 'banana', 'pear', 'duku', 'grape', 'longan']
langsat


In [3]:
fruits=['apple','durian','orange','banana','strawberry','mango','starfruit','rambutan']
fruits[3] = "duku" #change item at position 3 to "duku"
print(fruits)

#change items from position 4 to position 7
fruits[4:7] = ["pear", "grape", "guava"]
print(fruits)

#change items from position 4 to position 7 by ONE item
fruits[4:7] = ["mango"]
print(fruits)

#change items at position 4 with TWO items
#by using this change syntax, you CANNOT change last item!
fruits[4:5] = ["pear", "grape"]
print(fruits)

#change last item to "starfruit"
fruits[-1] = "starfruit"
print(fruits)

['apple', 'durian', 'orange', 'duku', 'strawberry', 'mango', 'starfruit', 'rambutan']
['apple', 'durian', 'orange', 'duku', 'pear', 'grape', 'guava', 'rambutan']
['apple', 'durian', 'orange', 'duku', 'mango', 'rambutan']
['apple', 'durian', 'orange', 'duku', 'pear', 'grape', 'rambutan']
['apple', 'durian', 'orange', 'duku', 'pear', 'grape', 'starfruit']


In [4]:
fruits=['apple', 'durian', 'duku', 'grape']

fruits.append("longan") # add an item at the end
print(fruits)

fruits.insert(3, "mango") #insert an item at position 3
print(fruits)

morefruits = ["rambutan", "strawberry"]
fruits.extend(morefruits) #insert morefruits at the end
print(fruits)

['apple', 'durian', 'duku', 'grape', 'longan']
['apple', 'durian', 'duku', 'mango', 'grape', 'longan']
['apple', 'durian', 'duku', 'mango', 'grape', 'longan', 'rambutan', 'strawberry']


In [5]:
fruits=['apple', 'durian', 'orange', 'banana', 'pear', 'duku', 'langsat', 'grape']

fruits.remove("orange") # remove the item by using value
print(fruits)

# remove the item at position 5 and assign to variable fruit
fruit = fruits.pop(5) 
print(fruits)
print(fruit)

fruits.pop() #remove the first item
print(fruits)

del fruits[1] #remove the item at position 1
print(fruits)

fruits.clear() #remove all values
print(fruits)

del fruits #remove the whole list
print(fruits) #error, cannot find this list

['apple', 'durian', 'banana', 'pear', 'duku', 'langsat', 'grape']
['apple', 'durian', 'banana', 'pear', 'duku', 'grape']
langsat
['apple', 'durian', 'banana', 'pear', 'duku']
['apple', 'banana', 'pear', 'duku']
[]


NameError: name 'fruits' is not defined

In [6]:
fruits=['apple', 'durian', 'orange', 'banana', 'pear', 'duku']

print(len(fruits)) #Length of List

if "guava" in fruits: # check if a fruit exists in the list
  print("Yes, the fruit is available in the fruit list") 

for fruit in fruits: #for each loop to access list items
  print(fruit)

6
apple
durian
orange
banana
pear
duku


In [7]:
fruits=['apple', 'durian', 'orange', 'banana']
fruits.sort() #Sort a List
print(fruits)

fruits.sort(reverse = True) #Sort in reverse order
print(fruits)

#Same as Java, it is object reference,
#cannot copy to a new List.
newfruits = fruits

#use .copy() to copy list items to a new list
newfruits = fruits.copy()
print(newfruits) 

#Join two lists to one list
fruits2 = ['pear', 'guava']
fruits3 = fruits + fruits2
print(fruits3)

['apple', 'banana', 'durian', 'orange']
['orange', 'durian', 'banana', 'apple']
['orange', 'durian', 'banana', 'apple']
['orange', 'durian', 'banana', 'apple', 'pear', 'guava']


In [8]:
fruits=('apple','durian','orange','banana','strawberry','mango','starfruit','rambutan')
print(fruits) #print all items
print(fruits[-1])

#This will return the items from position 1 to 5.
#The first item is position 0 and the LAST item "mango" is NOT included
print(fruits[1:5])

print(fruits[:5]) # extract value from poistion 0 to 5
print(fruits[5:]) # extract value from position 5 to the last one

# extract items from "banana" (-5) to, but NOT including "rambutan" (-1)
print(fruits[-5:-1])

('apple', 'durian', 'orange', 'banana', 'strawberry', 'mango', 'starfruit', 'rambutan')
rambutan
('durian', 'orange', 'banana', 'strawberry')
('apple', 'durian', 'orange', 'banana', 'strawberry')
('mango', 'starfruit', 'rambutan')
('banana', 'strawberry', 'mango', 'starfruit')


In [9]:
fruits=('apple','durian','orange','banana','strawberry')
#fruits[1] = "pear" #error

fruitslist = list(fruits) #convert to list
fruitslist[1] = "pear"
fruits = tuple(fruitslist) #convert back to tuple
print(fruits)

('apple', 'pear', 'orange', 'banana', 'strawberry')


In [10]:
import numpy as np
cars = np.array(['Honda','Toyota','BMW','Merz','Mazda','Proton'])
print(cars)
print(type(cars))
print(cars[3])

['Honda' 'Toyota' 'BMW' 'Merz' 'Mazda' 'Proton']
<class 'numpy.ndarray'>
Merz


In [1]:
import numpy as np

#0 Dimension, only a value
arr0 = np.array(44)
print(arr0)
print()
#1 Dimension, a list to an array
arr1 = np.array([747, 322, 870, 508])
print(arr1)
print()
#2 Dimension, an array contain more than one 1D array
arr2 = np.array([[747, 322], [507, 870], [508,638], [99, 81]])
print(arr2)
print()
#3 Dimension, an array contain more than one 2D array
arr3 = np.array([[[747, 322], [507, 870]], [[508, 638], [99, 81]]])
print(arr3)

44

[747 322 870 508]

[[747 322]
 [507 870]
 [508 638]
 [ 99  81]]

[[[747 322]
  [507 870]]

 [[508 638]
  [ 99  81]]]


In [12]:
#Casting range() to create a list from 1 to 9
arr = list(range(1,10))
print(arr)

#Create a list from 1 to 9 with step 2
arr = list(range(1,10,2))
print(arr)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 3, 5, 7, 9]
