In [4]:
import numpy as np
emptyarr = np.empty(10, dtype=int)
print(emptyarr)
cars=np.array(['Honda','Toyota','BMW','Merz','Mazda','Proton'])
print(cars)
print(type(cars))
print(cars[3])

[0 1 2 3 4 5 6 7 8 9]
['Honda' 'Toyota' 'BMW' 'Merz' 'Mazda' 'Proton']
<class 'numpy.ndarray'>
Merz


In [2]:
import numpy as np
#Create an array which initialize with 0 to 9
arr = np.arange(10)
print(arr)
#Create an array which initialize with:
#Start from 1, end with 10, step value 2
arr = np.arange(1,10,2)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [1]:
import numpy as np

#0 Dimension, only a value
arr0 = np.array(44)
print(arr0)
print()
#1 Dimension, a list to an array
arr1 = np.array([747, 322, 870, 508])
print(arr1)
print()
#2 Dimension, an array contain more than one 1D array
arr2 = np.array([[747, 322], [507, 870], [99,81]])
print(arr2)
print()
#3 Dimension, an array contain more than one 2D array
arr3 = np.array([[[747, 322], [507, 870]], [[508, 638], [99, 81]]])
print(arr3)

44

[747 322 870 508]

[[747 322]
 [507 870]
 [ 99  81]]

[[[747 322]
  [507 870]]

 [[508 638]
  [ 99  81]]]


In [2]:
import numpy as np

arr0 = np.array(44)
arr1 = np.array([747, 322, 870, 508])
arr2 = np.array([[747, 322], [507, 870], [99,81]])
arr3 = np.array([[[747, 322], [507, 870]], [[508, 638], [99, 81]]])

#Show Dimension of an array
print(arr0.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


In [ ]:
import numpy as np
#Create an array with 4 Dimension
arr = np.array([8, 9, 6, 4], ndmin=4)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[8 9 6 4]]]]
number of dimensions : 4


In [ ]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
#Print arr from position 1 to 5 with step 2
print(arr[1:5:2])

#Print the whole arr from with step 3
print(arr[::3])


[1 3]
[0 3 6]


In [ ]:
import numpy as np
arr = np.array([[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11]])

#First parameter is the position of 1-D array, 
#here is position 1, [6, 7, 8, 9, 10, 11]
#Second parameter is the position of the above array
#here are from position 1 to 4 (not include 4)
print(arr[1, 1:4])

#Seleact all 1-D array,
#each 1-D array select position 2 to 4
print(arr[:, 2:4])


[7 8 9]
[[2 3]
 [8 9]]


In [ ]:
import numpy as np
arr = np.array([[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11]])

#Show the size of 1-D arrays in the 2-D arr
print(arr.shape)

(2, 6)


In [ ]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

#reshape 1-D array to 2-D array which is 4 rows x 3 columns
#the size of 1-D array MUST be 4 x 3 =12 in this example
arr2d = arr.reshape(4, 3)
print(arr2d)
print()

#reshape 1-D array to 3-D array which contains 
#2 2-D arrays, and each 2-D array contain 3 1-D array,
#and each 1-D array contain 2 elements.
#The size of the above 1-D array MUST be 2x3x2 =12 in this example
arr3d = arr.reshape(2, 3, 2)
print(arr3d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [3]:
import numpy as np
arr = np.array([7, 8, 5, 3, 7, 1, 6])

#search value in array which is equal to 7
search = np.where(arr == 7)
print(search)

#search value in array which is divisible by 3
search = np.where(arr%3 == 0)
print(search)

(array([0, 4], dtype=int64),)
(array([3, 6], dtype=int64),)


In [4]:
import numpy as np
arr = np.array([7, 8, 5, 3, 7, 1, 6])

sorted = np.sort(arr)
print(sorted)

#search the poistion of first matched value in array 
#which is equal to 8
search = np.searchsorted(sorted, 8)
print(search)

[1 3 5 6 7 7 8]
6


In [5]:
import numpy as np
arr = np.array([7, 8, 5, 3, 7, 1, 6])
#Manually create a filter array by using True or False
filter = [False, False, True, False, True, False, True]
filterarr = arr[filter]
print(filterarr)

#Create a filter array by using a logical expression
filter = arr > 6
filterarr = arr[filter]

print(filterarr)

[5 7 6]
[7 8 7]


In [6]:
import numpy as np
arr = np.array([7, 8, 5, 3, 7, 1, 6])
#Delete an item at position 3
arr = np.delete(arr, 3)
print(arr) 
#Delete items at position 1, 4, 5
arr = np.delete(arr, [1, 4, 5])
print(arr)

[7 8 5 7 1 6]
[7 5 7]
